---
title: 'Chapter 8: Conditions'
author: "Paulo Magalang"
date: "2022-11-03"
output: 
  html_document: 
    keep_md: yes
---

# 8.1 Quiz

1. What are the three most important types of condition?

2. What function do you use to ignore errors in block of code?

3. What is the main difference between `tryCatch()` and `withCallingHandlers()`?

4. Why might you want to create a custom error object?


```{r}
library(rlang)
```


# 8.2 Signalling conditions

* three condtions

  - errors: function cannot continue and stops execution
  
  - warnings: function can partially recover but something went wrong
  
  - messages

  - keyboard interrupt (Esc, CTRL + C), only interactively
  
## 8.2.1 Errors

* errors are thrown by `stop()`

```{r, eval=FALSE}
f <- function() g()
g <- function() h()
h <- function() stop("This is an error!")

f()
```

```{r, eval=FALSE}
h <- function() stop("This is an error!", call. = FALSE)
f()
```

* rlang equivalent is `rlang::abort()`

```{r, eval = FALSE}
h <- function() abort("This is an error!")
f()
```


## 8.2.2 Warnings

* can have multiple warnings from a single function call

```{r}
fw <- function() {
  cat("1\n")
  warning("W1")
  cat("2\n")
  warning("W2")
  cat("3\n")
  warning("W3")
}

fw()
```

* `options(warn = 1)` makes warnings appear immediately

* `options(warn = 2)` to turn warnings into errors

* `options(warn = 0)` is default behavior

* rlang equivalent is `rlang::warn()`

## 8.2.3 Messages

```{r}
fm <- function() {
  cat("1\n")
  message("M1")
  cat("2\n")
  message("M2")
  cat("3\n")
  message("M3")
}

fm()
```

* `cat()` is for the user, `message()` for the developer 

## 8.2.4 Exercises

1. Write a wrapper around `file.remove()` that throws an error if the file to be
deleted does not exist.

```{r}
file.remove.err <- function(file) {
    out <- file.remove(file)
    if (out == FALSE) {
        abort(paste0(file, " does not exist"))
    }
}
```

2. What does the `appendLF` argument to `message()` do? How is it related to `cat()`?

`appendLF` appends a newline to the end of the message.

# 8.3 Ignoring conditions

* ignore errors with `try()`

* ignore warnings with `suppressWarnings()`

* ignore messages with `suppressMessages()`

```{r}
f2 <- function(x) {
  try(log(x)) # throws an error but execution continues
  10
}
f2("a")
```

* can assign within a `try()` call to set a default value if the code is not successful

```{r, eval = FALSE}
default <- NULL
try(default <- read.csv("possibly-bad-input.csv"), silent = TRUE)

default
```

```{r}
suppressWarnings({
  warning("Uhoh!")
  warning("Another warning")
  1
})

suppressMessages({
  message("Hello there")
  2
})

suppressWarnings({
  message("You can still see me")
  3
})
```

# 8.4 Handling conditions

* handlers can temporarily override or supplement default behaviors of conditions

```{r, eval = FALSE}
tryCatch(
  error = function(cnd) {
    # code to run when error is thrown
  },
  code_to_run_while_handlers_are_active
)

withCallingHandlers(
  warning = function(cnd) {
    # code to run when warning is signalled
  },
  message = function(cnd) {
    # code to run when message is signalled
  },
  code_to_run_while_handlers_are_active
)
```

* `tryCatch()` defines exiting handlers

* `withCallingHandlers()` defines calling handlers

## 8.4.1 Condition objects

```{r}
cnd <- catch_cnd(stop("An error"))
str(cnd)
```

## 8.4.2 Exiting handlers

```{r}
# return NA instead of throwing an error
f3 <- function(x) {
  tryCatch(
    error = function(cnd) NA,
    log(x)
  )
}

f3("x")
```

```{r}
# code executes normally if signaled condition does not match
tryCatch(
  error = function(cnd) 10,
  1 + 1
)

tryCatch(
  error = function(cnd) 10,
  {
    message("Hi!")
    1 + 1
  }
)
```

* are exiting handlers because after the condition is signaled, control passes
to the handler and never returns to the original code

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    message("Here")
    stop("This code is never run!")
  }
)
```

* `cnd` is the argument for the handler function

```{r}
tryCatch(
  error = function(cnd) {
    paste0("--", conditionMessage(cnd), "--")
  },
  stop("This is an error")
)
```

* `finally` in `tryCatch()` specifies a block of code to run regardless of
whether the initial expression succeeds or fails

```{r}
path <- tempfile()
tryCatch(
  {
    writeLines("Hi!", path)
    # ...
  },
  finally = {
    # always run
    unlink(path)
  }
)
```

## 8.4.3 Calling handlers

* code execution continues normally once the handler returns in calling handlers

```{r}
tryCatch(
  message = function(cnd) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)

withCallingHandlers(
  message = function(cnd) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

```{r}
withCallingHandlers(
  message = function(cnd) message("Second message"),
  message("First message")
)
```

```{r}
# Bubbles all the way up to default handler which generates the message
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)

# Bubbles up to tryCatch
tryCatch(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

```{r}
# Muffles the default handler which prints the messages
withCallingHandlers(
  message = function(cnd) {
    cat("Level 2\n")
    cnd_muffle(cnd) # stop here
  },
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)

# Muffles level 2 handler and the default handler
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) {
      cat("Level 1\n")
      cnd_muffle(cnd) # stop here
    },
    message("Hello")
  )
)
```

## 8.4.4 Call stacks

* call stacks of exiting vs calling handlers

```{r}
f <- function() g()
g <- function() h()
h <- function() message("!")
```

```{r}
# in context of the call that signalled the condition
withCallingHandlers(f(), message = function(cnd) {
  lobstr::cst()
  cnd_muffle(cnd)
})
```

```{r}
# in context of the call to tryCatch()
tryCatch(f(), message = function(cnd) lobstr::cst())
```

## 8.4.5 Exercises

1. What extra information does the condition generated by `abort()` contain
compared to the condition generated by `stop()` ie. what's the difference between
these two objects? Read the help for `?abort` to learn more.

`abort()` saves the backtrace of the error condition.

```{r}
stop_cnd <- catch_cnd(stop("An error"))
abort_cnd <- catch_cnd(abort("An error"))
str(stop_cnd)
str(abort_cnd)
```

2. Predict the results of evaluating the following code

```{r}
show_condition <- function(code) {
  tryCatch(
    error = function(cnd) "error",
    warning = function(cnd) "warning",
    message = function(cnd) "message",
    {
      code
      NULL
    }
  )
}

show_condition(stop("!")) # error
show_condition(10) # no matches, NULL
show_condition(warning("?!")) # warning

show_condition({ # message
  10
  message("?") # stops here
  warning("?!")
})

show_condition({ # warning 
  10
  warning("?") # stops here
  message("?!")
})
```

3. Explain the results of running this code:

```{r}
withCallingHandlers(
  message = function(cnd) message("b"),
  withCallingHandlers(
    message = function(cnd) message("a"),
    message("c")
  )
)

# message("c") is run, bubbles up to outer calling handler
# b is printed, then the inner calling handler is run, a is printed
# now message("a") is evaluated which bubbles out to the outer calling handler
# b is printed
# the original message("c") is now evaluated
```

4. Read the source code for `catch_cnd()` and explain how it works.

skip

```{r, eval = FALSE}
catch_cnd <- function(expr, classes = "condition") {
  stopifnot(is_character(classes))
  handlers <- rep_named(classes, list(identity))

  eval_bare(rlang::expr(
    tryCatch(!!!handlers, { # !!! splice operator, injects list of arguments into function call
      force(expr) # force evaluation of input expression
      return(NULL)
    })
  ))
}
```










5. How could you rewrite `show_condition()` to use a single handler?

```{r}
show_condition <- function(code) {
  tryCatch(
    error = function(cnd) "error",
    warning = function(cnd) "warning",
    message = function(cnd) "message",
    {
      code
      NULL
    }
  )
}
```

```{r}
show_condition_q5 <- function(code) {
  tryCatch(
    condition = function(cnd) {
        cnd_var <<- cnd
        obj_attributes <- attributes(cnd) # will be set null for a non object
        if(!is.null(obj_attributes)) {
            # check class of object
            obj_class <- obj_attributes$class[2]
            
            if (obj_class == "error") {
                "error"
            } else if (obj_class == "warning") {
                "warning"
            } else if (obj_class == "message") {
                "message"
            }
        }
    },
    {
        code
        NULL
    }
  )
}
show_condition_q5(stop("!")) # error
show_condition_q5(10) # no matches, NULL
show_condition_q5(warning("?!")) # warning
show_condition_q5({ # message
  10
  message("?") # stops here
  warning("?!")
})
```

# 8.5 Custom conditions

```{r, eval = FALSE}
# general pattern for creating custom conditions
abort(
  "error_not_found",
  message = "Path `blah.csv` not found", 
  path = "blah.csv"
)
```

## 8.5.1 Motivation

```{r, eval = FALSE}
my_log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort(paste0(
      "`x` must be a numeric vector; not ", typeof(x), "."
    ))
  }
  if (!is.numeric(base)) {
    abort(paste0(
      "`base` must be a numeric vector; not ", typeof(base), "."
    ))
  }

  base::log(x, base = base)
}

my_log(letters)
my_log(1:10, base = letters)
```

## 8.5.2 Signaling

```{r}
abort_bad_argument <- function(arg, must, not = NULL) {
  msg <- glue::glue("`{arg}` must {must}")
  if (!is.null(not)) {
    not <- typeof(not)
    msg <- glue::glue("{msg}; not {not}.")
  }
  
  abort("error_bad_argument", 
    message = msg, 
    arg = arg, 
    must = must, 
    not = not
  )
}
```

```{r}
# custom error without dependency on rlang
stop_custom <- function(.subclass, message, call = NULL, ...) {
  err <- structure(
    list(
      message = message,
      call = call,
      ...
    ),
    class = c(.subclass, "error", "condition")
  )
  stop(err)
}

err <- catch_cnd(
  stop_custom("error_new", "This is a custom error", x = 10)
)
class(err)
err$x
```

```{r, eval = FALSE}
my_log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort_bad_argument("x", must = "be numeric", not = x)
  }
  if (!is.numeric(base)) {
    abort_bad_argument("base", must = "be numeric", not = base)
  }

  base::log(x, base = base)
}

my_log(letters)
my_log(1:10, base = letters)
```

## 8.5.3 Handling

```{r, eval = FALSE}
library(testthat)

err <- catch_cnd(my_log("a"))

attributes(err)
expect_s3_class(err, "error_bad_argument")

err$arg
expect_equal(err$arg, "x")

err$not
expect_equal(err$not, "character")
```

```{r}
# use tryCatch to handle specific error by class, put most specific handlers first
tryCatch(
  error_bad_argument = function(cnd) "bad_argument",
  error = function(cnd) "other error",
  my_log("a")
)
```

## 8.5.4 Exercises

1. Inside a package, it's occasionally useful to check that a package is installed before
using it. Write a function that checks if a package is installed (with 
`requireNamespace("pkg", quietly = FALSE)`) and if not, throws a custom condition that
includes the package name in the metadata.)

```{r, eval = FALSE}
check_package_installed <- function(package) {
    #is_installed <- requireNamespace(package, quietly = FALSE)
    
    if(!is.character(package)) {
        abort(
            "bad_argument",
            message = paste0("`package` must be a character vector; not ", typeof(package), ".")
            )
    }
    if(!requireNamespace(package, quietly = FALSE)) {
        abort(
            "package_not_found",
            message = paste0(package, " is not installed. Install with `install.packages(", package, ")`."),
            package = package
            )
    }
    
    on.exit(unloadNamespace(package))
    cat(paste0(package, " is installed."))
}
# not super happy with this solution. requireNamespace will load in the package
# if it is installed and would rather just have a means to check if it is
# installed without loading it in
# and yes i know you can supress the message from requireNamespace by setting
# quietly = TRUE but I'm working within the parameters of the question relax

check_package_installed("ggplot2")
check_package_installed("ggplot")
check_package_installed(10)
```

2. Inside a package you often need to stop an error when something is not right.
Other packages that depend on your package might be tempted to check these errors
in their unit tests. How could you help these packages to avoid relying on the
error message which is part of the user interface rather than the API and might
change without notice?


# 8.6 Applications

## 8.6.1 Failure value

```{r}
fail_with <- function(expr, value = NULL) {
  tryCatch(
    error = function(cnd) value,
    return(expr) # return default value
  )
}

fail_with(log(10), NA_real_)
fail_with(log("x"), NA_real_)
```

```{r}
# watered-down version of base::try()
try2 <- function(expr, silent = FALSE) {
  tryCatch(
    error = function(cnd) {
      msg <- conditionMessage(cnd)
      if (!silent) {
        message("Error: ", msg)
      }
      structure(msg, class = "try-error")
    },
    expr
  )
}

try2(1)
try2(stop("Hi"))
try2(stop("Hi"), silent = TRUE)
```

## 8.6.2 Success and failure values

```{r}
foo <- function(expr) {
  tryCatch(
    error = function(cnd) error_val, # return error_val if code fails
    {
      expr
      success_val # return success_val if code is successful
    }
  )
}
```

```{r}
does_error <- function(expr) {
  tryCatch(
    error = function(cnd) TRUE,
    {
      expr
      FALSE
    }
  )
}
```

```{r}
catch_cnd <- function(expr) {
  tryCatch(
    condition = function(cnd) cnd, 
    {
      expr
      NULL
    }
  )
}
```

```{r}
# return result and error to determine if code succeeded or failed
safety <- function(expr) {
  tryCatch(
    error = function(cnd) {
      list(result = NULL, error = cnd)
    },
    list(result = expr, error = NULL)
  )
}

str(safety(1 + 10))
str(safety(stop("Error!")))
```

## 8.6.3 Resignal

```{r}
warning2error <- function(expr) {
  withCallingHandlers(
    warning = function(cnd) abort(conditionMessage(cnd)), # throw an error when handling a warning
    expr
  )
}
```

```{r, eval = FALSE}
warning2error({
  x <- 2 ^ 4
  warn("Hello")
})
```

## 8.6.4 Record

```{r, eval = FALSE}
catch_cnds <- function(expr) {
  conds <- list() # init output object
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd)) # append
    cnd_muffle(cnd)
  }
  
  withCallingHandlers(
    message = add_cond,
    warning = add_cond,
    expr
  )
  
  conds # return output object
}

catch_cnds({
  inform("a")
  warn("b")
  inform("c")
})
```

```{r, eval = FALSE}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }
  
  tryCatch( # also capture errors
    error = function(cnd) {
      conds <<- append(conds, list(cnd))
    },
    withCallingHandlers(
      message = add_cond,
      warning = add_cond,
      expr
    )
  )
  
  conds
}

catch_cnds({
  inform("a")
  warn("b")
  abort("C")
})
```

## 8.6.5 No default behavior

```{r}
log <- function(message, level = c("info", "error", "fatal")) {
  level <- match.arg(level)
  signal(message, "log", level = level) # no default handler
}

log("This code was run") # condition was signaled but no output
```

```{r}
# recods all logging messages into a file
record_log <- function(expr, path = stdout()) {
  withCallingHandlers(
    log = function(cnd) {
      cat(
        "[", cnd$level, "] ", cnd$message, "\n", sep = "",
        file = path, append = TRUE
      )
    },
    expr
  )
}

record_log(log("Hello"))
```

```{r}
ignore_log_levels <- function(expr, levels) {
  withCallingHandlers(
    log = function(cnd) {
      if (cnd$level %in% levels) {
        cnd_muffle(cnd)
      }
    },
    expr
  )
}

record_log(ignore_log_levels(log("Hello"), "info")) # ignore "info" logging level
```

## 8.6.6 Exercises

1. Create `suppressConditions()` that works like `suppressMessages()` and
`suppressWarnings()` but suppresses everything. Think carefully about how you
should handle errors.

From `suppressMessages` and `suppressWarnings`:

```
# suppressMessages
function (expr, classes = "message") 
withCallingHandlers(expr, message = function(c) if (inherits(c, 
    classes)) tryInvokeRestart("muffleMessage"))
<bytecode: 0x0000018b81eabc10>
<environment: namespace:base>

# suppressWarnings
function (expr, classes = "warning") 
{
    withCallingHandlers(expr, warning = function(w) if (inherits(w, 
        classes)) 
        tryInvokeRestart("muffleWarning"))
}
<bytecode: 0x0000018b81ea9a08>
<environment: namespace:base>
```

```{r}
suppressConditions <- function(expr) { # no need to define classes argument
    tryCatch(
        # what to do with errors?
        # inspo from 8.6.1 and https://stackoverflow.com/questions/19111956/suppress-error-message-in-r
        error = function(cnd) try(expr, silent = TRUE),
        condition = function(cnd) {
            # check if cnd is a message or warning
            if (inherits(cnd, "message")) {
                tryInvokeRestart("muffleMessage")
            } else if (inherits(cnd, "warning")) {
                tryInvokeRestart("muffleWarning")
            }
        },
        expr
    )
}
```

```{r}
suppressConditions(stop("Hi"))
suppressConditions(log10("a"))
suppressConditions(message("Hi"))

suppressConditions(log10(10))
```

2. Compare the following two implementations of `message2error()`. What is the main
advantage of `withCallingHanlders()` in this scenario? (Hint: look carefully at the
traceback.)

```{r}
message2error_1 <- function(code) {
  withCallingHandlers(code, message = function(e) stop(e))
}
message2error_2 <- function(code) {
  tryCatch(code, message = function(e) stop(e))
}
```

```{r, eval = FALSE}
message2error_1(message("a"))
traceback()

message2error_1(stop("a"))
traceback()
```

```{r, FALSE}
message2error_2(message("a"))
traceback()

message2error_2(stop("a"))
traceback()
```

3. How would you modify the `catch_cnds()` definition if you wanted to recreate the original
intermingling of warnings and messages?

See 8.6.4

4. Why is catching interrupts dangerous? Run this code to find out.

Imagine purposely destroying your emergency brakes. Yeah don't do that lol




































